displayName=Runecrafting Tracker
author=hBurt
support=https://github.com/mcscoobe/runecrafting-tracker
description=Track your total profit and the amount of runes you have crafted
tags=rc,rune,craft,runecraft,runecrafting,track,tracker,zmi,ourania,altar
plugins=com.runecraftingtracker.RunecraftingTrackerPlugin